#define HAS_16BIT_COLOR 0x1
#define HAS_W_CHANNEL 0x2
#define HAS_DITHER 0x4

#define INFO_PACKET 0x1
#define DATA_PACKET 0x2
#define KEEPALIVE_PACKET 0x3
#define TIMESTAMP_PACKET 0x4
#define ADD_ACTION_PACKET 0x5
#define REMOVE_ACTION_PACKET 0x6